### ISSUE TITLE
Overall Summary

### ISSUE THREAD

**Issue by jlag34** [AthenaX3/codecademy#6]
### Criteria 1: Node.js Project Structure
* _Score Level: 4/4
* _Comment(s): Project was very clean. Function declared underneath API.

### Criteria 2: Implementation of API Specification and Functionality
* _Score Level: 4/4
* _Comment(s): All of the functions did exactly what they should. All functions were very efficient.

### Criteria 3: Test Case Results
* _Score Level: 4/4
* _Comment(s): All tests pass!

### Criteria 4: JavaScript Fundamentals and Formatting
* _Score Level: 4/4
* _Comment(s): Excellent job demonstrating you have a clear understanding of the JavaScript fundamentals.

### Overall Score: 16/16

You did an excellent job on your project. Nice job getting all of the tests to pass! I like that you did all of the logic underneath your API using function declarations so that hoisting allowed you to set the values in the API. Also, good job using `const` where you should instead of always using `let`. Nice use of array methods and conditional statements. Lastly, nice job always setting the correct response status for different situations. All in all, keep up the great work!

**Comment by AthenaX3** [comment]
Thanks!
